version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/module:cached
      - foundry-data:/module/tmp/foundry:cached
    command: sleep infinity
    network_mode: service:foundry

  foundry:
    build:
      context: .
      dockerfile: Dockerfile-foundry
    init: true
    volumes:
      - foundry-data:/data
      - ./foundryScripts:/data/scripts
    environment:
      - CONTAINER_PRESERVE_OWNER=/data/Data
      - CONTAINER_VERBOSE=true
      - CONTAINER_PATCHES=/data/scripts
    env_file:
      - ../.env
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
      - 8080:8080


volumes:
  foundry-data:
    