ARG FOUNDRY_VERSION=develop

FROM felddy/foundryvtt:${FOUNDRY_VERSION}

WORKDIR ${FOUNDRY_HOME}

COPY ./admin.mjs ./adminPage.html ./

EXPOSE 80/TCP

ENTRYPOINT [ "./admin.mjs" ]
CMD ["resources/app/main.mjs", "--port=30000", "--headless", "--noupdate",\
  "--dataPath=/data"]